export enum Tech {
	HTML = "html",
	CSS = "css",
	JS = "js",
	TS = "ts",
	REACT = "react",
	NODEJS = "nodejs",
	PWA = "pwa",
	PRISMA = "prisma",
	POSTGRES = "postgres",
	REMIX = "remix",
	I18N = "i18n",
	TW = "tailwind",
	ZUSTAND = "zustand",
	SWR = "swr",
	VUE = "vue",
	SUPABASE = "supabase",
	PINIA = "pinia",
}
