/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fractured-rock.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { Vector3, type Mesh, type MeshStandardMaterial } from "three";
import { type GLTF } from "three-stdlib";

import { FRACTURE_RIGID_BODY_PROPS } from "../../../consts/fracture-rigid-body-props.const";
import { GROUP_PROPS } from "../../../consts/group-props.const";
import { RIGID_BODY_PROPS } from "../../../consts/rigid-body-props.const";

type GLTFResult = GLTF & {
	nodes: {
		Curve_cell: Mesh;
		Curve_cell001: Mesh;
		Curve_cell002: Mesh;
		Curve_cell003: Mesh;
		Curve_cell004: Mesh;
		Curve_cell005: Mesh;
		Curve_cell006: Mesh;
		Curve_cell007: Mesh;
		Curve_cell010: Mesh;
		Curve_cell011: Mesh;
		Curve_cell012: Mesh;
		Curve_cell013: Mesh;
		Curve_cell015: Mesh;
		Curve_cell016: Mesh;
		Curve_cell017: Mesh;
		Curve_cell018: Mesh;
		Curve_cell019: Mesh;
		Curve_cell020: Mesh;
	};
	materials: {
		["SVGMat.001"]: MeshStandardMaterial;
	};
};

export function FracturedRock(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/fractured-rock.glb"
	) as GLTFResult;

	return (
		<group
			{...GROUP_PROPS}
			scale={
				new Vector3(
					Number(RIGID_BODY_PROPS.scale) * 0.33 * 2,
					Number(RIGID_BODY_PROPS.scale) * 0.33 * 2,
					Number(RIGID_BODY_PROPS.scale)
				)
			}
			{...props}
			dispose={null}
		>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.219, 1.807, -0.001]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell001.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.844, 2.062, -0.178]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell002.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.115, 3.096, -0.021]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell003.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.674, 2.762, -0.112]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell004.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.632, 3.291, -0.033]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell005.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.138, 1.018, 0.03]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell006.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.795, 3.144, 0.025]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell007.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.094, 0.369, -0.09]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell010.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.792, 3.145, 0.17]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell011.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.296, 0.405, 0.188]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell012.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.863, 0.803, -0.001]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell013.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.482, 0.546, 0.036]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell015.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.271, 1.469, -0.085]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell016.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.246, 1.123, 0.075]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell017.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.89, 0.528, -0.059]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell018.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.273, 2.297, 0.042]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell019.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.681, 0.301, 0.036]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.Curve_cell020.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.49, 1.737, -0.005]}
				/>
			</RigidBody>
		</group>
	);
}

useGLTF.preload("/models/fractured-rock.glb");
