/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fractured-paper.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { type GLTF } from "three-stdlib";

import { FRACTURE_RIGID_BODY_PROPS } from "../../../consts/fracture-rigid-body-props.const";
import { GROUP_PROPS } from "../../../consts/group-props.const";

import type * as THREE from "three";

type GLTFResult = GLTF & {
	nodes: {
		hand_5__cell: THREE.Mesh;
		hand_5__cell001: THREE.Mesh;
		hand_5__cell002: THREE.Mesh;
		hand_5__cell003: THREE.Mesh;
		hand_5__cell004: THREE.Mesh;
		hand_5__cell005: THREE.Mesh;
		hand_5__cell006: THREE.Mesh;
		hand_5__cell007: THREE.Mesh;
		hand_5__cell008: THREE.Mesh;
		hand_5__cell009: THREE.Mesh;
		hand_5__cell010: THREE.Mesh;
		hand_5__cell011: THREE.Mesh;
		hand_5__cell012: THREE.Mesh;
		hand_5__cell013: THREE.Mesh;
		hand_5__cell014: THREE.Mesh;
		hand_5__cell015: THREE.Mesh;
		hand_5__cell016: THREE.Mesh;
		hand_5__cell017: THREE.Mesh;
		hand_5__cell018: THREE.Mesh;
		hand_5__cell019: THREE.Mesh;
		hand_5__cell020: THREE.Mesh;
		hand_5__cell021: THREE.Mesh;
		hand_5__cell022: THREE.Mesh;
		hand_5__cell023: THREE.Mesh;
		hand_5__cell024: THREE.Mesh;
		hand_5__cell025: THREE.Mesh;
	};
	materials: {
		["SVGMat.001"]: THREE.MeshStandardMaterial;
	};
};

export function FracturedPaper(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/fractured-paper.glb"
	) as GLTFResult;

	return (
		<group {...GROUP_PROPS} {...props} dispose={null}>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.013, 2.964, 0.032]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell001.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.595, 3.138, 0.011]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell002.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.362, 3.159, 0.008]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell003.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.172, 2.844, 0.026]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell004.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.421, 2.269, 0.064]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell005.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.971, 2.821, -0.071]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell006.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.303, 3.135, -0.101]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell007.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.045, 2.981, -0.159]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell008.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.491, 3.098, 0.17]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell009.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.135, 1.467, -0.008]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell010.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.365, 2.445, -0.03]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell011.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.875, 3.108, -0.032]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell012.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.843, 2.511, -0.036]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell013.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.393, 1.492, 0.01]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell014.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.478, 3.323, -0.014]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell015.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.266, 1.215, -0.012]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell016.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.249, 3.054, 0.134]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell017.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.213, 2.656, -0.04]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell018.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.793, 2.932, 0.14]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell019.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.822, 1.915, -0.073]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell020.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.003, 2.08, -0.009]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell021.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.875, 3.274, 0.056]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell022.geometry}
					material={materials["SVGMat.001"]}
					position={[-0.567, 3.008, 0.186]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell023.geometry}
					material={materials["SVGMat.001"]}
					position={[-1.45, 2.173, 0.01]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell024.geometry}
					material={materials["SVGMat.001"]}
					position={[-3.282, 2.574, 0.085]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.hand_5__cell025.geometry}
					material={materials["SVGMat.001"]}
					position={[-2.581, 3.36, 0.187]}
				/>
			</RigidBody>
		</group>
	);
}

useGLTF.preload("/models/fractured-paper.glb");
