/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fractured-scissors.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { type GLTF } from "three-stdlib";

import { FRACTURE_RIGID_BODY_PROPS } from "../../../consts/fracture-rigid-body-props.const";
import { GROUP_PROPS } from "../../../consts/group-props.const";

import type * as THREE from "three";

type GLTFResult = GLTF & {
	nodes: {
		path1_cell: THREE.Mesh;
		path1_cell002: THREE.Mesh;
		path1_cell003: THREE.Mesh;
		path1_cell004: THREE.Mesh;
		path1_cell005: THREE.Mesh;
		path1_cell006: THREE.Mesh;
		path1_cell007: THREE.Mesh;
		path1_cell008: THREE.Mesh;
		path1_cell009: THREE.Mesh;
		path1_cell010: THREE.Mesh;
		path1_cell011: THREE.Mesh;
		path1_cell012: THREE.Mesh;
		path1_cell013: THREE.Mesh;
		path1_cell014: THREE.Mesh;
		path1_cell015: THREE.Mesh;
		path1_cell016: THREE.Mesh;
		path1_cell017: THREE.Mesh;
		path1_cell018: THREE.Mesh;
		path1_cell019: THREE.Mesh;
		path1_cell020: THREE.Mesh;
		path1_cell021: THREE.Mesh;
		path1_cell022: THREE.Mesh;
		path1_cell023: THREE.Mesh;
	};
	materials: {
		["SVGMat.002"]: THREE.MeshStandardMaterial;
	};
};

export function FracturedScissors(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/fractured-scissors.glb"
	) as GLTFResult;

	return (
		<group {...GROUP_PROPS} {...props} dispose={null}>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.986, 1.054, 0.076]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell002.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.049, 0.866, -0.149]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell003.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.945, 2.1, 0.169]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell004.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.59, 1.839, 0.033]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell005.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.42, 1.662, 0.104]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell006.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.039, 2.785, 0.016]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell007.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.447, 0.664, 0.144]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell008.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.497, 1.465, 0.02]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell009.geometry}
					material={materials["SVGMat.002"]}
					position={[-0.473, 2.391, 0.178]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell010.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.147, 1.202, -0.038]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell011.geometry}
					material={materials["SVGMat.002"]}
					position={[-0.865, 1.045, -0.013]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell012.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.428, 1.735, 0.007]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell013.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.196, 2.181, -0.009]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell014.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.113, 1.712, -0.015]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell015.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.935, 2.552, 0.189]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell016.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.868, 0.724, -0.08]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell017.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.335, 1.896, -0.056]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell018.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.624, 2.88, 0.187]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell019.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.403, 2.556, 0.037]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell020.geometry}
					material={materials["SVGMat.002"]}
					position={[-2.91, 1.871, -0.132]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell021.geometry}
					material={materials["SVGMat.002"]}
					position={[-1.195, 2.424, -0.011]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell022.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.04, 1.614, -0.016]}
				/>
			</RigidBody>
			<RigidBody {...FRACTURE_RIGID_BODY_PROPS}>
				<mesh
					geometry={nodes.path1_cell023.geometry}
					material={materials["SVGMat.002"]}
					position={[-3.145, 1.77, 0.035]}
				/>
			</RigidBody>
		</group>
	);
}

useGLTF.preload("/models/fractured-scissors.glb");
