/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scissors.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody, type RigidBodyProps } from "@react-three/rapier";
import { Euler, type Mesh, type MeshStandardMaterial } from "three";
import { type GLTF } from "three-stdlib";

import { RIGID_BODY_PROPS } from "../../../consts/rigid-body-props.const";

type GLTFResult = GLTF & {
	nodes: {
		path1: Mesh;
		path3: Mesh;
		path4: Mesh;
		path5: Mesh;
		path6: Mesh;
		path7: Mesh;
	};
	materials: {
		["SVGMat.002"]: MeshStandardMaterial;
		["SVGMat.003"]: MeshStandardMaterial;
		["SVGMat.005"]: MeshStandardMaterial;
		["SVGMat.006"]: MeshStandardMaterial;
		["SVGMat.007"]: MeshStandardMaterial;
		["SVGMat.008"]: MeshStandardMaterial;
	};
};

interface ScissorsProps extends RigidBodyProps {
	groupProps?: JSX.IntrinsicElements["group"];
}

export function Scissors({ groupProps, ...props }: ScissorsProps) {
	const { nodes, materials } = useGLTF("/models/scissors.glb") as GLTFResult;

	const rotation = new Euler(Math.PI / 2, Math.PI / 2, 0);

	return (
		<RigidBody {...RIGID_BODY_PROPS} {...props}>
			<group {...props} dispose={null} rotation={[0, 0, 0]}>
				<mesh
					geometry={nodes.path1.geometry}
					material={materials["SVGMat.002"]}
					rotation={rotation}
					scale={100}
				/>
				<mesh
					geometry={nodes.path3.geometry}
					material={materials["SVGMat.003"]}
					rotation={rotation}
					scale={100}
				/>
				<mesh
					geometry={nodes.path4.geometry}
					material={materials["SVGMat.005"]}
					rotation={rotation}
					scale={100}
				/>
				<mesh
					geometry={nodes.path5.geometry}
					material={materials["SVGMat.006"]}
					rotation={rotation}
					scale={100}
				/>
				<mesh
					geometry={nodes.path6.geometry}
					material={materials["SVGMat.007"]}
					rotation={rotation}
					scale={100}
				/>
				<mesh
					geometry={nodes.path7.geometry}
					material={materials["SVGMat.008"]}
					rotation={rotation}
					scale={100}
				/>
			</group>
		</RigidBody>
	);
}

useGLTF.preload("/models/scissors.glb");
